### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/InventoryDecrapifier#10]
```
// I blame Dinnerbone.

Time: 4/30/18 10:54 PM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:643)
	at com.gamebuster19901.inventory.decrapifier.common.PlayerPickupQueue.contains(PlayerPickupQueue.java:26)
	at com.gamebuster19901.inventory.decrapifier.server.ServerDecrapifier.onPickup(ServerDecrapifier.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_ServerDecrapifier_onPickup_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:479)
	at net.minecraft.entity.item.EntityItem.onCollideWithPlayer(EntityItem.java:435)
	at net.minecraft.entity.player.EntityPlayer.collideWithPlayer(EntityPlayer.java:664)
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:635)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2396)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:272)
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423)
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:643)
	at com.gamebuster19901.inventory.decrapifier.common.PlayerPickupQueue.contains(PlayerPickupQueue.java:26)
	at com.gamebuster19901.inventory.decrapifier.server.ServerDecrapifier.onPickup(ServerDecrapifier.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_ServerDecrapifier_onPickup_EntityItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:479)
	at net.minecraft.entity.item.EntityItem.onCollideWithPlayer(EntityItem.java:435)
	at net.minecraft.entity.player.EntityPlayer.collideWithPlayer(EntityPlayer.java:664)
	at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:635)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2396)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:272)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 398
	Entity Name: Player829
	Entity's Exact location: 250.03, 70.00, 215.99
	Entity's Block location: World: (250,70,215), Chunk: (at 10,4,7 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423)
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@7677bcf
Stacktrace:
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 497256320 bytes (474 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version            | Source                           | Signature |
	|:--------- |:--------- |:------------------ |:-------------------------------- |:--------- |
	| UCHIJAAAA | minecraft | 1.12.2             | minecraft.jar                    | None      |
	| UCHIJAAAA | mcp       | 9.42               | minecraft.jar                    | None      |
	| UCHIJAAAA | FML       | 8.0.99.99          | forgeSrc-1.12.2-14.23.3.2655.jar | None      |
	| UCHIJAAAA | forge     | 14.23.3.2655       | forgeSrc-1.12.2-14.23.3.2655.jar | None      |
	| UCHIJAAAA | invdecrap | 0.11.1.17 - 1.12.2 | bin                              | None      |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [EntityPlayerMP['Player829'/398, l='New World', x=250.03, y=70.00, z=215.99], EntityPlayerMP['Gamebuster19901'/29144, l='New World', x=246.39, y=70.00, z=215.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Gamebuster19901** [comment]
Superseded by #11
